### ISSUE TITLE
Decimal exponents

### ISSUE THREAD

**Issue by Protected** [Daninet/exactnumber#5]
Math.pow or \** (which you're using under the hood) support decimal numbers as exponents. Is there any particular reason why your pow function must reject decimal exponents?

**Comment by Daninet** [comment]
That's because the ExactNumber cannot represent irrational numbers in an exact way. By allowing fractional numbers to the exponent, the result might be irrational:
`3^0.5 = sqrt(3) = 1.73205... (irrational number)`

Although it supports approximations for this case using the pow() function from the root:
```
const lib = require("exactnumber")
lib.pow(3, lib.ExactNumber('0.5'), 5).toString() // 1.73205
```
